# Generated by Django 3.1.7 on 2022-02-03 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='social_login',
            field=models.CharField(choices=[('g', 'google')], max_length=1, null=True, verbose_name='소셜 로그인'),
        ),
    ]
