# Generated by Django 3.1.7 on 2022-02-04 08:07

import django.core.management.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_social_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='nickname',
        ),
        migrations.AddField(
            model_name='user',
            name='secret_key',
            field=models.CharField(default=django.core.management.utils.get_random_secret_key, max_length=255),
        ),
    ]
